2022-06-25 17:13:47,883 INFO    MainThread:21928 [wandb_setup.py:_flush():76] Loading settings from /home/mira/.config/wandb/settings
2022-06-25 17:13:47,883 INFO    MainThread:21928 [wandb_setup.py:_flush():76] Loading settings from /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/settings
2022-06-25 17:13:47,883 INFO    MainThread:21928 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-25 17:13:47,883 INFO    MainThread:21928 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-06-25 17:13:47,883 INFO    MainThread:21928 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2022-06-25 17:13:47,883 INFO    MainThread:21928 [wandb_init.py:_log_setup():428] Logging user logs to /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171347-3ia47cav/logs/debug.log
2022-06-25 17:13:47,884 INFO    MainThread:21928 [wandb_init.py:_log_setup():429] Logging internal logs to /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171347-3ia47cav/logs/debug-internal.log
2022-06-25 17:13:47,884 INFO    MainThread:21928 [wandb_init.py:init():462] calling init triggers
2022-06-25 17:13:47,884 INFO    MainThread:21928 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {}
2022-06-25 17:13:47,884 INFO    MainThread:21928 [wandb_init.py:init():481] re-initializing run, found existing run on stack: 2iz5o20z
2022-06-25 17:13:47,891 ERROR   MainThread:21928 [wandb_init.py:init():1026] error
Traceback (most recent call last):
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 494, in init
    self._wl._global_run_stack[-1].finish()
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1678, in finish
    return self._finish(exit_code, quiet)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1684, in _finish
    tel.feature.finish = True
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/lib/telemetry.py", line 41, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 577, in _telemetry_callback
    self._telemetry_flush()
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 588, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 74, in _publish_telemetry
    self._publish(rec)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-06-25 17:13:50,156 INFO    MainThread:21928 [wandb_init.py:_pause_backend():341] pausing backend
2022-06-25 17:13:50,156 INFO    MainThread:21928 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-06-25 17:14:44,469 INFO    MainThread:21928 [wandb_init.py:_resume_backend():350] resuming backend
2022-06-25 17:14:44,510 INFO    MainThread:21928 [wandb_init.py:_pause_backend():341] pausing backend
2022-06-25 17:14:44,510 INFO    MainThread:21928 [jupyter.py:save_ipynb():377] not saving jupyter notebook
