Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 152, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 138, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 405, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Error in callback <function _WandbInit._resume_backend at 0x7ff3a436b670> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7ff3a436b430> (for post_run_cell):
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 170, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 127, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 395, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Error in callback <function _WandbInit._resume_backend at 0x7ff3a436b670> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7ff3a436b430> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7ff3a436b670> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7ff3a436b430> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7ff3a436b670> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7ff3a436b430> (for post_run_cell):
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.