2022-05-29 15:10:06,185 INFO    MainThread:9422 [internal.py:wandb_internal():90] W&B internal server running at pid: 9422, started at: 2022-05-29 15:10:06.185675
2022-05-29 15:10:06,187 INFO    WriterThread:9422 [datastore.py:open_for_write():75] open: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220529_151005-ohf9r1lf/run-ohf9r1lf.wandb
2022-05-29 15:10:06,188 DEBUG   SenderThread:9422 [sender.py:send():232] send: header
2022-05-29 15:10:06,188 DEBUG   SenderThread:9422 [sender.py:send():232] send: run
2022-05-29 15:10:06,306 DEBUG   HandlerThread:9422 [handler.py:handle_request():141] handle_request: check_version
2022-05-29 15:10:06,308 INFO    SenderThread:9422 [dir_watcher.py:__init__():197] watching files in: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220529_151005-ohf9r1lf/files
2022-05-29 15:10:06,309 INFO    SenderThread:9422 [sender.py:_start_run_threads():811] run started: ohf9r1lf with start time 1653851405
2022-05-29 15:10:06,309 DEBUG   SenderThread:9422 [sender.py:send():232] send: summary
2022-05-29 15:10:06,309 INFO    SenderThread:9422 [sender.py:_save_file():948] saving file wandb-summary.json with policy end
2022-05-29 15:10:06,309 DEBUG   SenderThread:9422 [sender.py:send_request():246] send_request: check_version
2022-05-29 15:10:06,415 DEBUG   HandlerThread:9422 [handler.py:handle_request():141] handle_request: run_start
2022-05-29 15:10:06,417 DEBUG   HandlerThread:9422 [meta.py:__init__():35] meta init
2022-05-29 15:10:06,417 DEBUG   HandlerThread:9422 [meta.py:__init__():49] meta init done
2022-05-29 15:10:06,417 DEBUG   HandlerThread:9422 [meta.py:probe():209] probe
2022-05-29 15:10:06,420 DEBUG   HandlerThread:9422 [meta.py:_setup_git():199] setup git
2022-05-29 15:10:07,188 INFO    WriterThread:9422 [datastore.py:close():279] close: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220529_151005-ohf9r1lf/run-ohf9r1lf.wandb
2022-05-29 15:10:07,314 INFO    Thread-7  :9422 [dir_watcher.py:_on_file_created():244] file/dir created: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220529_151005-ohf9r1lf/files/wandb-summary.json
2022-05-29 15:10:07,398 INFO    SenderThread:9422 [sender.py:finish():1110] shutting down sender
2022-05-29 15:10:07,398 INFO    SenderThread:9422 [dir_watcher.py:finish():312] shutting down directory watcher
2022-05-29 15:10:08,315 INFO    SenderThread:9422 [dir_watcher.py:finish():342] scan: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220529_151005-ohf9r1lf/files
2022-05-29 15:10:08,315 INFO    SenderThread:9422 [dir_watcher.py:finish():356] scan save: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220529_151005-ohf9r1lf/files/config.yaml config.yaml
2022-05-29 15:10:08,315 INFO    SenderThread:9422 [dir_watcher.py:finish():356] scan save: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220529_151005-ohf9r1lf/files/wandb-summary.json wandb-summary.json
2022-05-29 15:10:08,316 INFO    SenderThread:9422 [file_pusher.py:finish():145] shutting down file pusher
2022-05-29 15:10:08,316 INFO    SenderThread:9422 [file_pusher.py:join():150] waiting for file pusher
2022-05-29 15:10:08,784 INFO    Thread-12 :9422 [upload_job.py:push():132] Uploaded file /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220529_151005-ohf9r1lf/files/wandb-summary.json
2022-05-29 15:10:08,796 INFO    Thread-11 :9422 [upload_job.py:push():132] Uploaded file /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220529_151005-ohf9r1lf/files/config.yaml
2022-05-29 15:10:09,394 ERROR   MainThread:9422 [internal.py:wandb_internal():165] Thread HandlerThread:
Traceback (most recent call last):
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 265, in _process
    self._hm.handle(record)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 133, in handle
    handler(record)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 143, in handle_request
    handler(record)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 672, in handle_request_run_start
    run_meta.probe()
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/internal/meta.py", line 230, in probe
    self._setup_git()
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/internal/meta.py", line 205, in _setup_git
    self.data["root"] = self._git.root or self.data["root"] or os.getcwd()
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/wandb/sdk/lib/git.py", line 46, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/miras/anaconda3/envs/gpy/lib/python3.9/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: unsafe repository ('/D/MIT-WHOI/github_repos/syn_model' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /D/MIT-WHOI/github_repos/syn_model'
2022-05-29 15:10:11,410 INFO    MainThread:9422 [internal.py:handle_exit():80] Internal process exited
