2022-06-25 17:11:58,850 INFO    MainThread:23549 [internal.py:wandb_internal():90] W&B internal server running at pid: 23549, started at: 2022-06-25 17:11:58.850246
2022-06-25 17:11:58,851 INFO    WriterThread:23549 [datastore.py:open_for_write():75] open: /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171158-2iz5o20z/run-2iz5o20z.wandb
2022-06-25 17:11:58,853 DEBUG   SenderThread:23549 [sender.py:send():235] send: header
2022-06-25 17:11:58,853 DEBUG   SenderThread:23549 [sender.py:send():235] send: run
2022-06-25 17:11:59,129 DEBUG   HandlerThread:23549 [handler.py:handle_request():141] handle_request: check_version
2022-06-25 17:11:59,147 INFO    SenderThread:23549 [dir_watcher.py:__init__():205] watching files in: /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171158-2iz5o20z/files
2022-06-25 17:11:59,147 INFO    SenderThread:23549 [sender.py:_start_run_threads():812] run started: 2iz5o20z with start time 1656202318
2022-06-25 17:11:59,148 DEBUG   SenderThread:23549 [sender.py:send():235] send: summary
2022-06-25 17:11:59,148 INFO    SenderThread:23549 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2022-06-25 17:11:59,149 DEBUG   SenderThread:23549 [sender.py:send_request():249] send_request: check_version
2022-06-25 17:11:59,373 DEBUG   HandlerThread:23549 [handler.py:handle_request():141] handle_request: run_start
2022-06-25 17:11:59,374 DEBUG   HandlerThread:23549 [meta.py:__init__():35] meta init
2022-06-25 17:11:59,374 DEBUG   HandlerThread:23549 [meta.py:__init__():49] meta init done
2022-06-25 17:11:59,374 DEBUG   HandlerThread:23549 [meta.py:probe():209] probe
2022-06-25 17:11:59,375 DEBUG   HandlerThread:23549 [meta.py:_setup_git():199] setup git
2022-06-25 17:11:59,853 INFO    WriterThread:23549 [datastore.py:close():279] close: /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171158-2iz5o20z/run-2iz5o20z.wandb
2022-06-25 17:12:00,153 INFO    Thread-7  :23549 [dir_watcher.py:_on_file_created():256] file/dir created: /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171158-2iz5o20z/files/wandb-summary.json
2022-06-25 17:12:00,365 INFO    SenderThread:23549 [sender.py:finish():1111] shutting down sender
2022-06-25 17:12:00,366 INFO    SenderThread:23549 [dir_watcher.py:finish():336] shutting down directory watcher
2022-06-25 17:12:01,156 INFO    SenderThread:23549 [dir_watcher.py:finish():366] scan: /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171158-2iz5o20z/files
2022-06-25 17:12:01,156 INFO    SenderThread:23549 [dir_watcher.py:finish():380] scan save: /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171158-2iz5o20z/files/config.yaml config.yaml
2022-06-25 17:12:01,157 INFO    SenderThread:23549 [dir_watcher.py:finish():380] scan save: /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171158-2iz5o20z/files/wandb-summary.json wandb-summary.json
2022-06-25 17:12:01,168 INFO    SenderThread:23549 [file_pusher.py:finish():145] shutting down file pusher
2022-06-25 17:12:01,168 INFO    SenderThread:23549 [file_pusher.py:join():150] waiting for file pusher
2022-06-25 17:12:01,823 INFO    Thread-12 :23549 [upload_job.py:push():132] Uploaded file /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171158-2iz5o20z/files/wandb-summary.json
2022-06-25 17:12:01,824 INFO    Thread-11 :23549 [upload_job.py:push():132] Uploaded file /dos/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220625_171158-2iz5o20z/files/config.yaml
2022-06-25 17:12:02,276 ERROR   MainThread:23549 [internal.py:wandb_internal():165] Thread HandlerThread:
Traceback (most recent call last):
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 265, in _process
    self._hm.handle(record)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 133, in handle
    handler(record)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 143, in handle_request
    handler(record)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 672, in handle_request_run_start
    run_meta.probe()
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/internal/meta.py", line 230, in probe
    self._setup_git()
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/internal/meta.py", line 205, in _setup_git
    self.data["root"] = self._git.root or self.data["root"] or os.getcwd()
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/wandb/sdk/lib/git.py", line 46, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/mira/anaconda3/envs/gpytorch/lib/python3.9/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: unsafe repository ('/dos/MIT-WHOI/github_repos/syn_model' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /dos/MIT-WHOI/github_repos/syn_model'
2022-06-25 17:12:04,286 INFO    MainThread:23549 [internal.py:handle_exit():80] Internal process exited
